const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // Generate auto skill registry at build time (方案 A - comptime code generation)
    scanAndUpdateAutoRegistry(b);

    // Get zwasm dependency
    const zwasm_dep = b.dependency("zwasm", .{
        .target = target,
        .optimize = optimize,
        .tests = false,
    });

    const mod = b.addModule("kimiz", .{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .imports = &.{
            .{ .name = "zwasm", .module = zwasm_dep.module("zwasm") },
        },
    });

    const exe = b.addExecutable(.{
        .name = "kimiz",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "kimiz", .module = mod },
            },
        }),
    });

    exe.root_module.addIncludePath(b.path("ffi"));
    exe.root_module.addLibraryPath(b.path("ffi"));
    exe.root_module.linkSystemLibrary("fff_c", .{});

    b.installArtifact(exe);

    const run_step = b.step("run", "Run the app");
    const run_cmd = b.addRunArtifact(exe);
    run_step.dependOn(&run_cmd.step);
    run_cmd.step.dependOn(b.getInstallStep());

    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const mod_tests = b.addTest(.{
        .root_module = mod,
    });
    const run_mod_tests = b.addRunArtifact(mod_tests);

    const exe_tests = b.addTest(.{
        .root_module = exe.root_module,
    });
    const run_exe_tests = b.addRunArtifact(exe_tests);

    // Integration tests
    const integration_tests_module = b.createModule(.{
        .root_source_file = b.path("tests/integration_tests.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "kimiz", .module = mod },
        },
    });

    const integration_tests = b.addTest(.{
        .root_module = integration_tests_module,
    });
    const run_integration_tests = b.addRunArtifact(integration_tests);

    const test_step = b.step("test", "Run tests");
    test_step.dependOn(&run_mod_tests.step);
    test_step.dependOn(&run_exe_tests.step);
    test_step.dependOn(&run_integration_tests.step);
}

/// Scan src/skills/auto/ directory and update registry.zig at build time.
/// This implements comptime auto-discovery (方案 A from T-101 spec).
fn scanAndUpdateAutoRegistry(b: *std.Build) void {
    const dir = std.fs.cwd().openDir("src/skills/auto", .{ .iterate = true }) catch |err| {
        std.debug.print("Warning: Cannot scan src/skills/auto/ ({s}), skipping auto registry generation\n", .{@errorName(err)});
        return;
    };
    defer dir.close();

    var files = std.ArrayList([]const u8).init(b.allocator);
    defer {
        for (files.items) |f| b.allocator.free(f);
        files.deinit();
    }

    var it = dir.iterate();
    while (it.next() catch null) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".zig")) continue;
        if (std.mem.eql(u8, entry.name, "registry.zig")) continue;
        if (!std.mem.startsWith(u8, entry.name, "auto_")) continue;

        const name = b.allocator.dupe(u8, entry.name) catch continue;
        files.append(name) catch continue;
    }

    sortStrings(files.items);

    const new_content = buildRegistryContent(b.allocator, files.items);
    defer b.allocator.free(new_content);

    const registry_path = "src/skills/auto/registry.zig";
    const existing = std.fs.cwd().readFileAlloc(b.allocator, registry_path, 64 * 1024) catch null;
    defer if (existing) |e| b.allocator.free(e);

    if (existing) |e| {
        if (std.mem.eql(u8, std.mem.trim(u8, e, " \n\r\t"), std.mem.trim(u8, new_content, " \n\r\t"))) {
            return;
        }
    }

    const file = std.fs.cwd().createFile(registry_path, .{}) catch |err| {
        std.debug.print("Error: Cannot write registry.zig ({s})\n", .{@errorName(err)});
        return;
    };
    defer file.close();
    file.writeAll(new_content) catch |err| {
        std.debug.print("Error: Failed to write registry.zig ({s})\n", .{@errorName(err)});
        return;
    };

    if (files.len > 0) {
        std.debug.print("Generated auto registry: {d} skill(s) detected\n", .{files.len});
    }
}

fn buildRegistryContent(allocator: std.mem.Allocator, files: []const []const u8) []const u8 {
    var buf = std.ArrayList(u8).init(allocator);
    const writer = buf.writer();

    writer.writeAll(
        \\//! Auto-generated skill registry (build-time)
        \\//! Generated by build.zig - DO NOT EDIT MANUALLY
        \\//! See T-101: Design AutoRegistry dynamic loading
        \\
        \\const skills = @import("../root.zig");
        \\
        \\pub fn registerAutoSkills(registry: *skills.SkillRegistry) !void {
        \\    @setEvalBranchQuota(10000);
        \\
    ) catch return "";

    if (files.len == 0) {
        writer.writeAll("    // No auto skills detected\n") catch return "";
    } else {
        for (files) |filename| {
            const line = std.fmt.allocPrint(allocator, "    try registry.register(@import(\"{s}\").getSkill());\n", .{filename}) catch return "";
            defer allocator.free(line);
            writer.writeAll(line) catch return "";
        }
    }

    writer.writeAll("}\n") catch return "";
    return buf.toOwnedSlice() catch return "";
}

fn sortStrings(arr: [][]const u8) void {
    if (arr.len < 2) return;
    var i: usize = 1;
    while (i < arr.len) : (i += 1) {
        var j: usize = i;
        while (j > 0 and std.mem.order(u8, arr[j - 1], arr[j]).compare(.gt)) {
            const tmp = arr[j - 1];
            arr[j - 1] = arr[j];
            arr[j] = tmp;
            j -= 1;
        }
    }
}
