//! Auto-generated skill registry (build-time)
//! Generated by tools/gen_auto_registry.sh - DO NOT EDIT MANUALLY
//! See T-101: Design AutoRegistry dynamic loading

const skills = @import("../root.zig");

pub fn registerAutoSkills(registry: *skills.SkillRegistry) !void {
    @setEvalBranchQuota(10000);
    try registry.register(@import("auto_hello.zig").getSkill());
}
