#!/bin/bash
# T-101: Auto-skill registry generator
# Scans src/skills/auto/ for auto_*.zig files and generates registry.zig

AUTO_DIR="src/skills/auto"
REGISTRY_FILE="$AUTO_DIR/registry.zig"

# Check if auto directory exists
if [ ! -d "$AUTO_DIR" ]; then
    exit 0
fi

# Collect auto skill files (excluding registry.zig, sorted for determinism)
SKILLS=()
for f in $(ls "$AUTO_DIR"/auto_*.zig 2>/dev/null | sort); do
    filename=$(basename "$f")
    SKILLS+=("$filename")
done

# Generate content
{
    echo '//! Auto-generated skill registry (build-time)'
    echo '//! Generated by tools/gen_auto_registry.sh - DO NOT EDIT MANUALLY'
    echo '//! See T-101: Design AutoRegistry dynamic loading'
    echo ''
    echo 'const skills = @import("../root.zig");'
    echo ''
    echo 'pub fn registerAutoSkills(registry: *skills.SkillRegistry) !void {'
    echo '    @setEvalBranchQuota(10000);'
    
    if [ ${#SKILLS[@]} -eq 0 ]; then
        echo '    // No auto skills detected'
    else
        for skill in "${SKILLS[@]}"; do
            echo "    try registry.register(@import(\"$skill\").getSkill());"
        done
    fi
    
    echo '}'
} > "${REGISTRY_FILE}.tmp"

# Only update if content changed (preserve cache)
if [ -f "$REGISTRY_FILE" ] && diff -q "$REGISTRY_FILE" "${REGISTRY_FILE}.tmp" > /dev/null 2>&1; then
    rm -f "${REGISTRY_FILE}.tmp"
else
    mv "${REGISTRY_FILE}.tmp" "$REGISTRY_FILE"
    if [ ${#SKILLS[@]} -gt 0 ]; then
        echo "Generated auto registry: ${#SKILLS[@]} skill(s) detected"
    fi
fi
